### ISSUE TITLE
Print Friendly and/or Export Feature

### ISSUE THREAD

**Issue by RyanMPierson** [getgrav/grav-theme-resume#1]
This might be the kind of thing that warrants its own plugin, but this theme in particular is desperately crying out to be print friendly. Currently, it doesn't seem to be.

![screen shot 2015-10-08 at 12 59 14 pm](https://cloud.githubusercontent.com/assets/4026828/10375510/735bbe32-6dbe-11e5-978b-ae38b57b6a5b.png)
![screen shot 2015-10-08 at 12 59 08 pm](https://cloud.githubusercontent.com/assets/4026828/10375509/735a040c-6dbe-11e5-9e9b-64ac985cf417.png)

What would really make this particular theme shine is a set of buttons near the top that enable export to PDF, print friendly, etc.

**Comment by hexplor** [comment]
I just did some tests :) It's doable :) I'm going to include printing layout in next update, after I release Halcyon. Not sure about PDF generation tho. Might need to research a little.

**Comment by hexplor** [comment]
Ok :) Printing layout added and fixed (in develop for now). If you can do a quick testing I would be grateful ;)

**Comment by RyanMPierson** [comment]
There is one section that is a little funky in a printout. 
![screen shot 2015-11-20 at 3 55 14 pm](https://cloud.githubusercontent.com/assets/4026828/11312988/3f472e4e-8f9f-11e5-90f6-856f8f8e4de5.png)

The Specialties one, which would be a difficult print. Not critical to me, but if there's a way to squish them a bit more so they line up it could be perfect.

**Comment by hexplor** [comment]
if you enable printing backgrounds, it will display fine :)
